DATALOADER:
  ROOT: data/fairface
  BATCH_SIZE: 128
  SHUFFLE: True
  NUM_WORKERS: 4
MODEL:
  PRETRAINED: False
  NUM_CLASSES: 6 #Background + Face
OPTIMIZER:
  LEARNING_RATE: 0.01
  MOMENTUM: 0.9
LR_SCHEDULER:
  MILESTONES:
  - 12
  - 17
  GAMMA: 0.1
TRAINER:
  NUM_OF_EPOCHS: 20